[package]
name = "mtgjson"
version = "0.0.0"
edition = "2021"
license = "GPL-3.0"
rust-version = "1.58.1"
authors = ["TylerBloom <tylerbloom2222@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = { version = "0.8", features = ["v5"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0.68" }
serde_with = { version = "1.5.1" }
